#!/usr/bin/env node
/**
 * concat-css.js
 *
 * cargo-leptos accepts exactly one CSS/SCSS entry via the
 * `[package.metadata.leptos] style-file = "..."` key. We have two
 * pieces of CSS that need to be served together on every page:
 *   - style/base.css         (hand-written design tokens + globals)
 *   - style/uno.generated.css (UnoCSS atomic utilities, regenerated
 *     from src/**\/*.rs by the @unocss/cli)
 *
 * This script concatenates them (base first, so utilities can
 * override defaults via specificity) and writes the result to
 * style/main.css, which cargo-leptos then hashes + minifies via
 * lightningcss.
 *
 * Order matters; do not reorder.
 *
 * Note: style/repo_graph.css is intentionally NOT bundled here --
 * it ships as a separate file under /repo_graph.css and is loaded
 * lazily by RepositoryGraph only when a project page mounts.
 */

const fs = require('node:fs');
const path = require('node:path');

const root = path.resolve(__dirname, '..');
const inputs = [
  path.join(root, 'style', 'base.css'),
  path.join(root, 'style', 'uno.generated.css'),
];
const output = path.join(root, 'style', 'main.css');

const banner = `/* DO NOT EDIT -- generated by scripts/concat-css.js. */\n`;
const parts = [banner];
for (const file of inputs) {
  if (!fs.existsSync(file)) {
    console.error(`concat-css: missing input ${file}`);
    process.exit(1);
  }
  parts.push(`/* === ${path.relative(root, file)} === */\n`);
  parts.push(fs.readFileSync(file, 'utf8'));
  parts.push('\n');
}
fs.writeFileSync(output, parts.join(''));
console.log(`concat-css: wrote ${output} (${parts.length - 1} parts)`);
